### ISSUE TITLE
Incompatibility with "Indium"

### ISSUE THREAD

**Issue by ghost** [Johni0702/fade-in-chunks#10]
> 
> 
> I don't see how this has anything to do with Java 11, did you even test Java 10 / older?
> 
> Duplicate of #8

After testing more carefully a sodium rev did managed to get in(so that was the actual problem), but eventually it led me to discover a possible incompatibilty with the mod "indium"
[crash-2021-04-09_17.06.24-client.txt](https://github.com/Johni0702/fade-in-chunks/files/6287101/crash-2021-04-09_17.06.24-client.txt)

_Originally posted by @Willimo in https://github.com/Johni0702/fade-in-chunks/issues/9#issuecomment-816772876_

**Comment by Johni0702** [comment]
From the [Indium README](https://github.com/comp500/Indium):
> Requires Sodium 1.16.x/next branch compiled from source

Fade In Chunks should not, in principle, be incompatible with Indium. It does only support the latest Sodium release though, whereas Indium requires a newer, not yet released, version, so they cannot currently be used at the same time.
