### ISSUE TITLE
Iris incompat. Both mods use different versions of Sodium.

### ISSUE THREAD

**Issue by Blunder-G** [Johni0702/fade-in-chunks#12]
Iris relased: https://irisshaders.github.io

But Iris and FadeInChunks use different type of versions.

Sodium is getting too much "Side version" and this can cause some problems...
I don't know how accurate it would be to suggest this, but is it possible to get Fade In Chunks in Sodium?

**Comment by Johni0702** [comment]
> But Iris and FadeInChunks use different type of versions.
>
>Sodium is getting too much "Side version" and this can cause some problems...

Fade In Chunks does not require a custom Sodium version, it requires the latest (at time of writing) official Sodium release.
It's Iris which requires a custom version and Iris' changes should eventually be merged into the official Sodium (though that doesn't mean that it'll automatically work with Fade In Chunks once that happens, see #11).

> I don't know how accurate it would be to suggest this, but is it possible to get Fade In Chunks in Sodium?

Pretty sure this would be considered out of scope for Sodium. It's a performance mod, not an eye candy mod.

**Comment by Razatop** [comment]
So there is no way to get these to mods to work together? Sad, I was hoping for shaders and the smooth chunk loading.
