### ISSUE TITLE
Entity distance is broken by this mod in combination with EntityCulling

### ISSUE THREAD

**Issue by CalXee** [Johni0702/fade-in-chunks#4]
Entity distance was broken in sodium but it was fixed in a recent commit in the /next branch. However this mod in combination with EntityCulling broke it again.

EntityCulling link: https://www.curseforge.com/minecraft/mc-mods/entityculling

Entity Distance fix commit: https://github.com/CaffeineMC/sodium-fabric/commit/9915466a81e9d5e32f03fe16b1902c1e4880d824

Note, the combination of those two mods probably didn't break entity distance itself, but Fade-in Chunks might have made some changes where it made EntityCulling think entities are not visible when they are, which happens to make entity distance useless.

Entity distance 500% without EntityCulling:
![2021-03-09_14 05 29](https://user-images.githubusercontent.com/68349758/110523864-adb0b200-80e0-11eb-8188-0c9d5d383402.png)

Entity distance 500% with EntityCulling:
![2021-03-09_14 07 04](https://user-images.githubusercontent.com/68349758/110524028-e0f34100-80e0-11eb-8683-531a2ac65d3e.png)

**Comment by Johni0702** [comment]
I see absolutely no plausible way for Fade In Chunks to have any effect on entity rendering at all. It doesn't remotely touch entity rendering and even for the part of Sodium which it does touch, it does not change the behavior but merely adds additional things. Only once the chunk data is on the GPU does it change the pixel color of the blocks.

Are you certain has anything to do with Fade In Chunks?

**Comment by Johni0702** [comment]
From the EntityCulling mod description:
> This mod calculates the visibility of tile/-entities 64 blocks in each direction of the player(so a 128x128x128 cube in total), everything outside of that is considered too far away and is invisible

**Comment by CalXee** [comment]
Yeah oops, I for some reason just never encountered it without this mod. Reported in EntityCulling issue page.
