### ISSUE TITLE
Crash with sodium built from source

### ISSUE THREAD

**Issue by ghost** [Johni0702/fade-in-chunks#8]
[crash-2021-04-03_15.43.18-client.txt](https://github.com/Johni0702/fade-in-chunks/files/6253714/crash-2021-04-03_15.43.18-client.txt)

**Comment by Johni0702** [comment]
Only the latest official Sodium release is supported (similar to how most mods only support the latest Minecraft release). If you want to build from source, checkout [`mc1.16.3-0.1.0`](https://github.com/CaffeineMC/sodium-fabric/tree/mc1.16.3-0.1.0) before building.
